import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:shishu_suraksha/app/theme/colors.dart';
import 'package:shishu_suraksha/data/models/child_model.dart';
import 'package:shishu_suraksha/data/services/storage_service.dart';
import 'package:shishu_suraksha/ui/widgets/glass_container.dart';
import 'package:intl/intl.dart';

class ReportsTab extends ConsumerStatefulWidget {
  const ReportsTab({super.key});

  @override
  ConsumerState<ReportsTab> createState() => _ReportsTabState();
}

class _ReportsTabState extends ConsumerState<ReportsTab> {
  List<ChildModel> _children = [];

  @override
  void initState() {
    super.initState();
    _loadChildren();
  }

  void _loadChildren() {
    setState(() {
      _children = ref.read(storageServiceProvider).getAllChildren();
    });
  }

  Future<void> _generateReport(ChildModel child) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('Shishu Suraksha - Child Health Report'),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Name: ${child.name}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Text('Date of Birth: ${DateFormat('dd/MM/yyyy').format(child.dob)}'),
              pw.Text('Gender: ${child.gender}'),
              pw.Text('Parent: ${child.parentName} (${child.parentPhone})'),
              pw.SizedBox(height: 20),
              pw.Text('Growth History', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Table.fromTextArray(
                context: context,
                data: <List<String>>[
                  <String>['Date', 'Height (cm)', 'Weight (kg)', 'Notes'],
                  ...child.growthHistory.map(
                    (item) => [
                      DateFormat('dd/MM/yyyy').format(item.date),
                      item.height.toString(),
                      item.weight.toString(),
                      item.notes ?? '-',
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Footer(
                leading: pw.Text('Generated by Shishu Suraksha AI'),
                trailing: pw.Text(DateFormat('dd/MM/yyyy hh:mm a').format(DateTime.now())),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Report_${child.name}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
               children: [
                 const Text(
                  'Reports',
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
                const Spacer(),
                IconButton(icon: const Icon(Icons.refresh, color: Colors.white), onPressed: _loadChildren),
               ],
            ),
          ),
          Expanded(
            child: _children.isEmpty
                ? const Center(
                    child: Text(
                      'No children found for reporting.',
                      style: TextStyle(color: Colors.white70),
                    ),
                  )
                : ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: _children.length,
                    itemBuilder: (context, index) {
                      final child = _children[index];
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 12.0),
                        child: GlassContainer(
                          child: ListTile(
                            leading: const Icon(Icons.picture_as_pdf, color: Colors.redAccent),
                            title: Text(
                              child.name,
                              style: const TextStyle(
                                fontWeight: FontWeight.bold,
                                color: AppColors.textPrimary,
                              ),
                            ),
                            subtitle: Text(
                              '${child.growthHistory.length} records available',
                              style: const TextStyle(color: AppColors.textSecondary),
                            ),
                            trailing: const Icon(Icons.download, color: AppColors.primary),
                            onTap: () => _generateReport(child),
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
